[package]
name = "rust_file_server"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2.3"     # To handle directory traversal
infer = "0.8"       # To detect file types
url-escape = "0.1.1"  # For decoding special characters in URLs